
name: kaalka
version: 4.0.0
description: Kaalka encryption algorithm for Dart. Robust, lossless time-based encryption for text and files/media using clock hand angles, trigonometric functions, and integer arithmetic. Cross-language compatible with Python and JavaScript.
homepage: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
repository: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  path: any
dev_dependencies:
  test: ^1.24.0