
name: kaalka
version: 5.0.0
description: "Kaalka encryption algorithm for Dart. Application-ready time protocol: envelope, seal, replay protection, file chunking, public API. Pure Kaalka time-based logic, no external crypto. Cross-language compatible with Python and JavaScript."
# keywords: time-based, encryption, protocol, envelope, seal, replay-protection, chunking, kaalka
homepage: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
repository: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  path: any
dev_dependencies:
  test: ^1.24.0