
name: kaalka
version: 3.0.0
description: Kaalka encryption algorithm for Dart. Time-based encryption for text and files using clock hand angles and trigonometric functions.
homepage: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
repository: https://github.com/PIYUSH-MISHRA-00/Kaalka-Encryption-Algorithm
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  path: any
dev_dependencies:
  test: ^1.24.0