name: Publish to npm

on:
  push:
    branches:
      - kaalka-javascript

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish --dry run --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Add your npm token as a GitHub secret
